<div id="index_vsebina">
    <div id="novice">
        <h1>Novice</h1>
        Lahko so splošne ali pa povezane z vsebino strani
    </div>
    <div id="oglas_dneva">
        <h1>Oglas dneva</h1>
        naključno izbran oglas, ali pa oglas ki ima največ ogledov
    </div>
    <div id="anketa">
        <h1>Anketa</h1>
        Anketa, z prikazom rezultatov v grafu ali torti
    </div>
    <div id="najnovejsi_oglasi">
        <h1>Najnovejši oglasi</h1>
        Prikaz zadnjih treh dodanih oglasov
    </div>
</div>
