<div class="span9" style="margin: -650px 0 0 27%;">
          <div class="hero-unit">
            <h1>Glavna novica!</h1>
            <p>Novica - text</p>
            <p><a class="btn btn-primary btn-large">Povezava &raquo;</a></p>
          </div>
          <div class="row-fluid" style="margin-left: 20px;">
            <div class="span4">
              <h2>Anketa</h2>
              <p>Anketa - Vsebina</p>
              <p><a class="btn" href="#">Glasuj &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Oglas dneva</h2>
              <p>Oglas dneva - text</p>
              <p><a class="btn" href="#">Povezava &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Novica</h2>
              <p>Novica - text</p>
              <p><a class="btn" href="#">Podrobnosti &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->