<div class="span9" style="margin: -520px 0 0 27%;">
          <div class="hero-unit">
              <h1><?php echo $this->news->getName(); ?></h1>
            <p><?php echo $this->news->getText(); ?></p>
            <p><a class="btn btn-primary btn-large">Urejanje &raquo;</a></p>
          </div>
          <div class="row-fluid" style="margin-left: 20px;">
            <div class="span4">
              <h2>Anketa</h2>
              <p>Vsebina ankete</p>
              <p><a class="btn" href="#">Glasuj &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Zadnji Oglas</h2>
              <p>Oglas</p>
              <p><a class="btn" href="#">Povezava &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->
        </div><!--/span-->