<div id="content">
    <div id="view-content">
        <h2>Novica uspešno aktivirana</h2>
        <hr />
        <a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'account',
                                        'action'     => 'news',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>" />
            <span class="ads_add">Nazaj</span>
        </a>
    </div>
</div>

