<div id="content">
    <div id="view-content-form">
        <h2>Novica uspešno izbrisana</h2>
        <a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'account',
                                        'action'     => 'news',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>" />
        Nazaj</a>
    </div>
</div>