<div id="content">
    <div id="view-content">
        <p><b>Podatki o uporabniku:</b></p>
        <table id="profile">
            <tr>
                <td><b>Username:</b></td>
                <td><?php echo "\$Username"; ?></td>
            </tr>
            <tr>
                <td><b>Password:</b></td>
                <td><?php echo "\$Password"; ?></td>
            </tr>
            <tr>
                <td><b>Email:</b></td>
                <td><?php echo "\$Email"; ?></td>
            </tr>
            <tr>
                <td><b>Status:</b></td>
                <td><?php echo "\$Status"; ?></td>
            </tr>
            <tr>
                <td><b>Name:</b></td>
                <td><?php echo "\$Name"; ?></td>
            </tr>
            <tr>
                <td><b>Surname:</b></td>
                <td><?php echo "\$Surname"; ?></td>
            </tr>
                <td><b>Telephon:</b></td>
                <td><?php echo "\$Telephon"; ?></td>
            </tr>
        </table>
    </div>
</div>

