<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Spletni Oglasnik</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Oglasi, mali oglasi, avtomobili, nepremičnine">
    <meta name="author" content="Sano fužir">

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/style.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>
    <link href="/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="ico/favicon.ico">
    <script src="chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl/document_iterator.js"></script>
    <script src="chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl/find_proxy.js"></script>
    <script src="chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl/get_html_text.js"></script>
    <script src="chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl/global_constants.js"></script>
    <script src="chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl/name_injection_builder.js"></script>
    <script src="chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl/number_injection_builder.js"></script>
    <script src="chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl/menu_injection_builder.js"></script>
    <script src="chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl/string_finder.js"></script>
    <script src="chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl/change_sink.js"></script>
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<?php echo $this->url(
                                    array(
                                        'controller' => 'index',
                                        'action'     => 'index',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Spletni Oglasnik</a>
          <div class="btn-group pull-right">
            <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="icon-user"></i>Username
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="<?php echo $this->url(
                                    array(
                                        'module' => 'default',
                                        'controller' => 'account',
                                        'action'     => 'profil',
                                        'id' => '1' //tukaj bo potem preko $_SESSION dobilo id userja
                                        
                                    ),
                                    'default',
                                    true) ?>">Profil</a></li>
              <li class="divider"></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'account',
                                        'action'     => 'register',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Registracija</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'account',
                                        'action'     => 'login',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Login</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'account',
                                        'action'     => 'logout',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Logout</a></li>
            </ul>
          </div>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="ctive"><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'index',
                                        'action'     => 'index',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Domov</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'account',
                                        'action'     => 'list',
                                        'module' => 'default',
                                        'id' => '1' //tukaj bo potem preko $_SESSION dobilo id userja
                                    ),
                                    'default',
                                    true) ?>">Moji Oglasi</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'contact',
                                        'action'     => 'index',
                                        'module' => 'default'                                        
                                    ),
                                    'default',
                                    true) ?>">Kontakti</a></li>
              <!--
              <li><a href="<?php /*echo $this->url(
                                    array(
                                        'controller' => 'guestbook',
                                        'action'     => 'index',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) */?>">Knjiga Gostov</a></li>
              -->
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'sponsor',
                                        'action'     => 'index',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Sponzorji</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'link',
                                        'action'     => 'index',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Povezave</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Spletni Oglasnik</li>
              <li class="active"><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'index',
                                        'action'     => 'view',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Novice</a></li>
              <li class="nav-header">Nepremičnine</li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'apartment',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Stanovanja</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'house',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Hiše</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'parcel',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Parcele</a></li>

              <li class="nav-header">Avto-moto</li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'car',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Avtomobili</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'truck',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Tovorna vozila</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'bike',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Motorna kolesa</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'motorhome',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Avtodomi</a></li>

              <li class="nav-header">Audio-video</li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'speaker',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Zvočniki</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'equipment',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Oprema</a></li>

              <li class="nav-header">Računalništvo</li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'pc',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">PC</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'mac',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Mac</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'server',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Strežniki</a></li>
              <li><a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'table',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">Tablice</a></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        
      </div><!--/row-->

      
<!--
      <footer>
        <p>&copy; Sano Fužir 2012</p>
      </footer>
-->
    </div><!--/.fluid-container-->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="/js/jquery.js"></script>
    <script src="/js/bootstrap-transition.js"></script>
    <script src="/js/bootstrap-alert.js"></script>
    <script src="/js/bootstrap-modal.js"></script>
    <script src="/js/bootstrap-dropdown.js"></script>
    <script src="/js/bootstrap-scrollspy.js"></script>
    <script src="/js/bootstrap-tab.js"></script>
    <script src="/js/bootstrap-tooltip.js"></script>
    <script src="/js/bootstrap-popover.js"></script>
    <script src="/js/bootstrap-button.js"></script>
    <script src="/js/bootstrap-collapse.js"></script>
    <script src="/js/bootstrap-carousel.js"></script>
    <script src="/js/bootstrap-typeahead.js"></script>

     <?php echo $this->layout()->content ?>
  </body>
</html>
