<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Spletni oglasnik</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header">
    <div id="header-logo">
        <b>SPLETNI OGLASNIK</b>
    </div>
    <div id="header-navigation">
        <ul>
            <a href="./"><li>Domov</li></a>
            <a href="<?php echo $this->url(
            array('controller'=>'oglasi'),
            'default',
            true) ?>"><li>Oglasi</li></a>
            <a href="<?php echo $this->url(
            array('controller'=>'prijava'),
            'default',
            true) ?>"><li>Prijava | Odjava</li></a>
            <a href="<?php echo $this->url(
            array('controller'=>'registracija'),
            'default',
            true) ?>"><li>Registracija</li></a>
            <a href="<?php echo $this->url(
            array('controller'=>'guestbook'),
            'default',
            true) ?>"><li>Guestbook</li></a>
        </ul>
    </div>
</div>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>