<div id="content">
    <div id="view-content">
        <div>
            <h1>Povezave:</h1>
            <ul id="links">
                <li><a href="https://www.google.si/">Google</a></li>
                <li><a href="http://www.php.net/">Php.net</a></li>
                <li><a href="http://www.w3schools.com/">W3schools</a></li>
                <li><a href="http://framework.zend.com/">Zend Framework</a></li>
                <li><a href="http://www.doctrine-project.org/">Doctrine project</a></li>
            </ul>
        </div>
    </div>
</div>

