<div id="content">
    <div id="view-content">
        <div id="ads">
            <!-- Izpis oglasov -->
            <h2 id="ads_h2">Oglasi v kategoriji <?php echo $this->category; ?>:</h2>
            <br />
            <?php foreach ($this->ads as $ad): ?>
                <div>
                    <a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'view',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>" />
                        <?php echo $ad->getName();?> -  
                        <?php echo $ad->getPrice()."€";?>
                        <br />
                    </a>                    
                </div>
            <?php endforeach; ?>
        </div>
    </div>
</div>

