<div id="content">
    <div id="view-content">
        <div id="ads">
            <a href="<?php echo $this->url(
                                    array(
                                        'controller' => 'ads',
                                        'action'     => 'add',
                                        'module' => 'default'
                                    ),
                                    'default',
                                    true) ?>">
                <img src="/img/add.png" alt="add">
                <span>Dodajanje oglasov</span>
            </a>
            <br />
            <!-- Izpis oglasov -->
            <h2 id="ads_h2">Oglasi:</h2>
            <?php
            $category=$this->_getParam('category');
            $this->_em->getRepository('pot do repositoryja')->findByName($category);
            
            
            ?>
            
        </div>
    </div>
</div>

