<div id="content">
    <div id="view-content">
        <div id="ads">
            <!-- Izpis oglasov -->
            <h2 id="ads_h2">Oglasi <?php echo "id:".$this->ad->getId(); ?></h2>          
                <ul>
                    <li>
                        <span class="podatki">Ime:</span> 
                            <?php echo $this->ad->getName();;?>
                    </li>
                    <li>
                        <span class="podatki">Cena:</span>
                            <?php echo number_format($this->ad->getPrice(), 2, ',', ' ')." €";?>
                    </li>
                    <li>
                        <span class="podatki">Opis: </span>
                            <?php echo $this->ad->getDescription();;?>
                    </li>
                    <li>
                        <span class="podatki">Datum:</span>
                            <?php echo date_format($this->ad->getCreated(), "d.m.Y"); ?>
                    </li>
                    <li><span class="podatki">Slike:</span><br /><br />
                        <?php 
                            
                            $str = $this->ad->getImage()->getName(); 
                            $lokacija = explode('/', $str);
                            echo ($lokacija[4]);
                        ?>
                        <a href="<?php echo "/".($lokacija[4]);  ?>" />
                            <img src="<?php echo "/".($lokacija[4]);  ?>" alt="slika">
                        </a>
                    </li>
                        
                </ul>
        </div>
    </div>
</div>


