<div id="content">
    <div id="view-content" style="width: 900px;">
        <h1>Sponzorji:</h1>
        <br />
        <div class="sponsors">
            <a href="http://www.inovis.si/">
                <h2>Inovis d.o.o:</h2>
                <img src="img/inovis_logo.png" alt="Inovis"/>
            </a>
        </div>
        <div class="sponsors">
            <a href="http://www.apple.com/">
                <h2>Apple:</h2>
                <img src="img/silver-apple-logo.png" alt="Apple"/>
            </a>
        </div>
        <div class="sponsors">
            <a href="http://www.microsoft.com/">
                <h2>Microsoft:</h2>
                <img src="img/microsoft-logo.jpg" alt="Microsoft"/>
            </a>
        </div>
        <div class="sponsors">
            <a href="http://vss.scv.si/">
                <h2>VSŠ Velenje:</h2>
                <img src="img/vss_50.png" alt="Vsš"/>
            </a>
        </div>
    </div>
</div>

